config/routes.rb
ItemTracker::Application.routes.draw do
  resources :weapons

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weapon }
      else
        format.html { render action: 'new' }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:weapon_name, :weapon_type, :weapon_dmg, :weapon_def)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItemTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Runescape Item Tracker</h1>
<%= yield %>

</body>
</html>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weapon_name %><br>
    <%= f.text_field :weapon_name %>
  </div>
  <div class="field">
    <%= f.label :weapon_type %><br>
    <%= f.text_field :weapon_type %>
  </div>
  <div class="field">
    <%= f.label :weapon_dmg %><br>
    <%= f.text_field :weapon_dmg %>
  </div>
  <div class="field">
    <%= f.label :weapon_def %><br>
    <%= f.text_field :weapon_def %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<h1>Listing weapons</h1>

<table>
  <thead>
    <tr>
      <th>Weapon name</th>
      <th>Weapon type</th>
      <th>Weapon dmg</th>
      <th>Weapon def</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.weapon_name %></td>
        <td><%= weapon.weapon_type %></td>
        <td><%= weapon.weapon_dmg %></td>
        <td><%= weapon.weapon_def %></td>
        <td><%= link_to 'Show', weapon %></td>
        <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
        <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weapon name:</strong>
  <%= @weapon.weapon_name %>
</p>

<p>
  <strong>Weapon type:</strong>
  <%= @weapon.weapon_type %>
</p>

<p>
  <strong>Weapon dmg:</strong>
  <%= @weapon.weapon_dmg %>
</p>

<p>
  <strong>Weapon def:</strong>
  <%= @weapon.weapon_def %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>

app/views/welcome/index.html.erb
<h1>Hi there, put something here!</h1>